version: "3.3"
services:

  mysql:
    image: mysql:${MYSQL_VERSION:-latest}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    volumes:
      - data:/var/lib/mysql
    container_name: mysql
    
  php:
    build: 
      context: './php/'
      args:
        PHP_VERSION: ${PHP_VERSION}
    volumes:
      - ./public_html/:/var/www/html/
    container_name: php

  apache:
    build:
      context: './apache/'
      args:
       APACHE_VERSION: ${APACHE_VERSION}
    depends_on:
      - php
      - mysql
    ports:
      - "80:80"
    volumes:
      - ./public_html/:/var/www/html/
    container_name: apache

volumes:
  data:
